services:
  - type: web
    name: neurocrow-client-manager
    env: go
    buildCommand: go build -o server
    startCommand: ./server
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false # This means you'll set it in Render dashboard